/* Approved Human First Flow. Existing cart/router remain; presentation is shared. */
const escapeFlow=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photo=(key,label='',extra='')=>`<span class="flow-photo photo-${key} ${extra}" role="img" aria-label="${escapeFlow(label||'Illustrative KudaratCare photography')}"></span>`;
const flowArrow=()=>ic('arrow');
const flowSample='<p class="flow-sample">Design preview: products, imagery and prices are illustrative. Nothing is purchased or booked.</p>';
const flowArticles=[
 {id:'skin-barrier',cat:'Skin',title:'Understanding your skin barrier',ex:'A gentler starting point for everyday skin care.',pic:'leaves',intro:'Your skin is more than what you see in the mirror. Its outer surface helps hold moisture in and protect against everyday exposure. Understanding that job is a useful starting point for a simpler routine.',parts:[['Keep the routine clear','A cleanser, moisturizer and appropriate sun protection are a useful framework to discuss with a qualified professional. More steps do not automatically mean a better routine.'],['Make room for questions','If a product feels uncomfortable or your skin changes persistently, speak with a qualified clinician rather than adding more products.']],read:4},
 {id:'hair-routine',cat:'Hair',title:'A simpler hair routine',ex:'Getting to know your hair without overcomplicating it.',pic:'hair',intro:'Hair care starts with noticing what your hair and scalp need, not with filling a shelf. Your washing habits, styling choices and the way your hair feels can all help shape that conversation.',parts:[['Start with your everyday habits','Think about how often you wash, how you style, and what you want from your routine. Keep product instructions close by and avoid assuming one routine suits everyone.'],['Ask when something changes','Persistent scalp discomfort or a noticeable change in hair shedding is a reason to seek individual advice from a qualified clinician.']],read:3},
 {id:'ingredients',cat:'Ingredients',title:'Getting to know your ingredients',ex:'A thoughtful look at the label behind the bottle.',pic:'ingredients',intro:'An ingredient list is a starting point, not a promise. It helps you understand what is in a product, but a familiar plant name does not tell you everything about how a formula will feel or suit your skin.',parts:[['Read the whole label','Check the ingredient list, directions, warnings and storage information. For this prototype, formulas and packaging are illustrative, not verified product specifications.'],['Natural still deserves care','Natural does not automatically mean suitable for every person. Bring questions about sensitivities and individual needs to a qualified professional.']],read:4},
 {id:'gifting-notes',cat:'Gifting',title:'The little details that make a gift',ex:'Thoughtful packaging, a personal note and everyday usefulness.',pic:'wedding',intro:'The most memorable gift often feels considered rather than complicated. The occasion, recipient and presentation can guide your choices.',parts:[['Begin with the person','Consider preferences and sensitivities before choosing skin or hair products for someone else.'],['Make the presentation personal','A short note, a useful box and a restrained ribbon can make a curated collection feel truly personal.']],read:3}
];
P.forEach(p=>{p.tag='';p.mrp=null;p.short='An illustrative product from the KudaratCare collection. Final formula, ingredients and directions will be supplied by the brand.'});
byId('sun-veil').name='Everyday Sun Care';
art=function(type){const key={pump:'cleanser',tube:'cleanser',jar:'cream',dropper:'serum',oil:'serum',mist:'cleanser',bar:'cream',box:'corporate',trunk:'corporate',tin:'wedding',potli:'wedding',candle:'ingredients'}[type]||'cream';return photo(key,'Illustrative product packaging')};
jart=function(cat){return photo(cat==='Hair'?'hair':cat==='Ingredients'?'ingredients':cat==='Bridal'?'wedding':'leaves','Illustrative Journal photography')};
const flowCards=a=>a.map(x=>`<a class="flow-journal" href="#/journal/${x.id}">${photo(x.pic,x.title)}<h3>${x.title}</h3><p>${x.ex}</p><span class="link">Read more ${flowArrow()}</span></a>`).join('');
let flowCategory='skin';
function flowCategoryCards(){
 const lists={skin:[['cleanser','Cleanser','neem-wash'],['cream','Moisturizer','saffron-cream'],['serum','Serum','kesar-elixir'],['hair','Hair care','amla-cleanser']],hair:[['hair','Hair cleanser','amla-cleanser'],['serum','Hair oil','bhringraj-oil'],['cream','Hair mask','hibiscus-mask'],['serum','Scalp serum','methi-serum']],kits:[['corporate','Daily care kit','glow-kit'],['corporate','Hair care kit','hair-kit'],['wedding','Wedding gifting','bride-plan'],['corporate','Corporate gifts','corp-signature']]};
 return lists[flowCategory].map(([key,title,id])=>`<a href="#/product/${id}" class="flow-category">${photo(key,title)}<span class="caption">${title}${flowArrow()}</span></a>`).join('');
}
Home=function(){return `
 <section class="flow-hero">${photo('hero','A relaxed woman in a softly sunlit room','hero-photo')}<div class="wrap"><div class="flow-hero-copy"><h1>Good care<br>starts with you.</h1><p>Skin, hair and a little guidance.</p><a href="#/consult" class="btn btn-teal">Book a consultation</a><a href="#/shop" class="link">Explore the shop ${flowArrow()}</a></div></div></section>
 <section class="flow-section"><div class="wrap"><div class="flow-heading"><h2>Your everyday essentials</h2><a href="#/shop" class="link">Visit the shop ${flowArrow()}</a></div><div class="flow-tabs" role="tablist" aria-label="Explore care categories">${[['skin','Skin'],['hair','Hair'],['kits','Build a routine']].map(([id,t])=>`<button role="tab" aria-controls="flowCategories" aria-selected="${flowCategory===id}" id="tab-${id}" data-flowcat="${id}">${t}</button>`).join('')}</div><div class="flow-categories" id="flowCategories" role="tabpanel" aria-labelledby="tab-${flowCategory}">${flowCategoryCards()}</div></div></section>
 <section class="flow-care">${photo('consult','Illustrative consultation conversation')}<div class="flow-care-copy"><h2>A little guidance<br>goes a long way.</h2><p>A conversation about your skin and hair, with space to ask questions and explore your next steps.</p><a href="#/consult" class="btn btn-teal">Explore consultations ${flowArrow()}</a></div></section>
 <section class="flow-section"><div class="wrap"><div class="flow-center"><h2>Care, beautifully gifted.</h2><p>Thoughtful collections for people and moments that matter.</p></div><div class="flow-gift-grid"><a href="#/shop/wedding" class="flow-gift">${photo('wedding','Ivory wedding gift boxes with flowers')}<div class="flow-gift-copy"><h3>Wedding gifting</h3><p>Considered details for your celebration, from favours to gifts for your closest people.</p><span class="link">Explore wedding gifts ${flowArrow()}</span></div></a><a href="#/shop/corporate" class="flow-gift">${photo('corporate','Teal corporate gift boxes with gold ribbon')}<div class="flow-gift-copy"><h3>Corporate gifting</h3><p>A thoughtful way to welcome, appreciate and celebrate teams and partners.</p><span class="link">Explore corporate gifts ${flowArrow()}</span></div></a></div></div></section>
 <section class="flow-section" style="padding-top:0"><div class="wrap"><div class="flow-heading"><h2>Kudarat Care Journal</h2><a href="#/journal" class="link">Read the Journal ${flowArrow()}</a></div><div class="flow-journal-grid">${flowCards(flowArticles.slice(0,3))}</div></div></section>
 <section class="flow-news"><div class="wrap"><div><h2>Stay close to good care.</h2><p>Notes on everyday care, thoughtful routines and new discoveries.</p></div><div><form class="inline-form" data-flowform="newsletter"><input type="email" placeholder="Your email" aria-label="Email for newsletter preview" required autocomplete="off"><button class="btn" type="submit">Subscribe</button></form><p style="font-size:12px;margin-top:10px">Preview only. No email is sent or saved.</p></div></div></section>`};
Consult=function(){return phero('Consult','Care starts with<br>a conversation.','Talk about your skin and hair, ask questions, and explore what comes next.','Consult',`<div class="hero-cta"><a href="#book" class="btn btn-teal" data-scroll="book">Explore a consultation ${flowArrow()}</a></div>`)+`
 <section class="flow-section"><div class="wrap"><h2>A clearer path to care.</h2><div class="flow-steps">${[['steth','Choose your focus','Skin or hair. Start with what is on your mind.'],['video','Make time to talk','Explore a consultation format that works for you.'],['leaf','Consider your next steps','A space for questions and individual guidance.']].map(([i,h,p])=>`<div class="flow-step">${ic(i)}<b>${h}</b><p>${p}</p></div>`).join('')}</div></div></section>
 <section class="flow-section" style="padding-top:0" id="book"><div class="wrap flow-book-grid"><div><h2>A little space<br>for your questions.</h2><p class="lead">Try the booking layout below. The final care team, availability, services and fees will be added once the client supplies them.</p>${photo('consult','Illustrative doctor and patient conversation')}</div><form class="card" data-flowform="booking"><h3 style="font-size:25px;margin-bottom:22px">Explore a consultation</h3><div class="fgrid"><div class="field full"><label for="focus">Your focus</label><select class="inp" id="focus" name="focus"><option>Skin care</option><option>Hair & scalp care</option><option>General care guidance</option></select></div><div class="field full"><label>Consultation format</label><div class="chips" data-chipgroup="format"><button class="chip on" type="button" data-chip="Video">Video</button><button class="chip" type="button" data-chip="In-person">In-person</button></div></div><div class="field full"><label for="flowDate">Sample date</label><input class="inp" id="flowDate" name="date" required type="date" min="${new Date().toLocaleDateString('en-CA')}" value=""></div><div class="field full"><label for="flowTime">Sample time</label><select class="inp" id="flowTime" name="time"><option>10:00 AM</option><option>11:30 AM</option><option>4:00 PM</option><option>5:30 PM</option></select></div><div class="full"><button class="btn btn-teal btn-block">Preview my booking</button>${flowSample}</div></div></form></div></section>`};
Shop=function(tab,params={}){
 if(params.category)shopState.cat=params.category;
 if(params.concern){shopState.concern=params.concern;shopState.cat='all'}
 const titles={'':['Everyday care,<br>thoughtfully chosen.','Explore the skin and hair collection, or find a thoughtful gift.'],wedding:['Care, beautifully<br>gifted.','Little details for your celebration and the people who make it special.'],corporate:['A thoughtful way<br>to say thank you.','Considered gifts for your teams, clients and everyday milestones.']};
 const [h,l]=titles[tab]||titles[''];
 return phero('Shop',h,l,tab==='wedding'?'Wedding gifting':tab==='corporate'?'Corporate gifting':'Shop')+`<section class="flow-section" style="padding-top:30px"><div class="wrap"><div class="seg" role="tablist" aria-label="Shop collections">${[['','Skin & hair','leaf'],['wedding','Wedding','gift'],['corporate','Corporate','brief']].map(([id,t,i])=>`<button role="tab" aria-selected="${tab===id}" class="${tab===id?'on':''}" data-go="#/shop${id?'/'+id:''}">${ic(i)}${t}</button>`).join('')}</div>${flowSample}${tab==='wedding'?Wedding():tab==='corporate'?Corporate():Catalog()}</div></section>`;
};
Catalog=function(){return `<div class="shopbar"><div class="chips">${[['all','All'],['skin','Skin'],['hair','Hair'],['kits','Kits']].map(([id,t])=>`<button class="chip ${shopState.cat===id?'on':''}" data-cat="${id}">${t}</button>`).join('')}</div><div style="display:flex;gap:12px;flex:1;justify-content:flex-end;flex-wrap:wrap"><div class="search">${ic('search')}<input class="inp" id="q" aria-label="Search products" placeholder="Search the collection" value="${escapeFlow(shopState.q)}"></div><select class="inp sort" id="concernSel" aria-label="Filter by concern"><option value="">All concerns</option>${CONCERNS.map(c=>`<option value="${c.id}" ${shopState.concern===c.id?'selected':''}>${c.name}</option>`).join('')}</select><select class="inp sort" id="sortSel" aria-label="Sort products"><option value="pop">Collection order</option><option value="lo" ${shopState.sort==='lo'?'selected':''}>Price: low to high</option><option value="hi" ${shopState.sort==='hi'?'selected':''}>Price: high to low</option></select></div></div><div class="grid g4" id="pgrid">${gridHTML()}</div><div class="flow-care" style="margin-top:55px;border-radius:12px;overflow:hidden">${photo('consult','Illustrative care conversation')}<div class="flow-care-copy"><h2>A little guidance<br>goes a long way.</h2><p>Explore a conversation about your skin and hair.</p><a href="#/consult" class="btn btn-teal">Explore consultations</a></div></div>`};
Wedding=function(){return `
 <div class="flow-inline-image">${photo('wedding','Wedding gifts on ivory fabric')}</div><div class="flow-heading" style="margin-top:42px"><h2>Gifts for your closest people.</h2></div><div class="grid g4">${P.filter(p=>p.cat==='wedding').map(pcard).join('')}</div>
 <div class="flow-steps">${[['gift','For your guests','Explore favours that bring a personal touch to every place setting.'],['heart','For your inner circle','Thoughtful collections for family, friends and the wedding party.'],['leaf','Make it yours','Explore packaging, a personal note and a palette to match the occasion.']].map(([i,h,p])=>`<div class="flow-step">${ic(i)}<b>${h}</b><p>${p}</p></div>`).join('')}</div>
 <div style="margin-top:55px" id="byob"><div class="flow-heading"><h2>Build a thoughtful gift.</h2></div><p class="flow-sample">Interactive sample builder. Quantities and estimates are placeholders, not confirmed business terms. Use sample names only.</p><div class="byob"><div id="byobSteps">${byobSteps()}</div><aside class="preview on-dark" id="byobPrev">${byobPreview()}</aside></div></div>`;
};
Corporate=function(){return `<div class="flow-inline-image">${photo('corporate','Teal corporate gifts with gold ribbons')}</div><div class="flow-heading" style="margin-top:42px"><h2>Considered collections.</h2></div><div class="grid g3">${P.filter(p=>p.cat==='corporate').map(pcard).join('')}</div>
 <div class="flow-steps">${[['brief','Welcome & appreciate','From a first day to a well-earned thank you.'],['gift','Make your mark','Explore a custom sleeve, note card or ribbon.'],['leaf','Curate with care','Choose a collection around the people receiving it.']].map(([i,h,p])=>`<div class="flow-step">${ic(i)}<b>${h}</b><p>${p}</p></div>`).join('')}</div>
 <div class="flow-book-grid" style="margin-top:55px" id="corpForm"><div><h2>Let us shape<br>your gifting brief.</h2><p class="lead">Explore the enquiry layout. Final quantities, pricing and delivery options will be confirmed by the brand.</p></div><form class="card" data-flowform="enquiry"><div class="fgrid"><div class="field full"><label for="occasion">Occasion</label><select class="inp" id="occasion"><option>Employee welcome</option><option>Client appreciation</option><option>Festive gifting</option><option>Events & milestones</option></select></div><div class="field"><label for="quantity">Sample quantity</label><select class="inp" id="quantity"><option>25 to 50</option><option>50 to 100</option><option>100+</option></select></div><div class="field"><label for="budget">Sample budget per gift</label><select class="inp" id="budget"><option>Under ₹1,000</option><option>₹1,000 to ₹2,000</option><option>₹2,000+</option></select></div><div class="field full"><label for="branding">Branding preference</label><select class="inp" id="branding"><option>Custom note card</option><option>Branded sleeve</option><option>Ribbon & packaging</option></select></div><div class="full"><button class="btn btn-teal btn-block">Preview enquiry ${flowArrow()}</button><p class="muted" style="font-size:13px;margin-top:14px">Preview only. No enquiry is sent.</p></div></div></form></div>`;
};
Product=function(id){
 const p=byId(id);if(!p)return NotFound();
 return `<section class="flow-section"><div class="wrap"><div class="crumbs" style="margin-bottom:24px"><a href="#/shop">Shop</a><span>/</span><span>${p.name}</span></div><div class="pd"><div class="pd-art">${art(p.type)}</div><div><span class="eyebrow">Sample collection</span><h1>${p.name}</h1><p class="lead" style="margin:20px 0">${p.short}</p><div class="price" style="font-size:24px">${inr(p.price)} <small style="font-size:13px;font-weight:400">sample price</small></div><div class="chips sizes" data-chipgroup="size" style="margin:24px 0">${p.sizes.map((s,i)=>`<button class="chip ${i===0?'on':''}" data-chip="${s}">${s}</button>`).join('')}</div><div style="display:flex;gap:12px;align-items:center;margin:24px 0"><div class="qty-ctl"><button data-pq="-1" aria-label="Decrease quantity">${ic('minus')}</button><span id="pq">1</span><button data-pq="1" aria-label="Increase quantity">${ic('plus')}</button></div><button class="btn btn-teal" style="flex:1" data-addpd="${p.id}">Add to bag ${ic('bag')}</button></div>${flowSample}${acc('About this sample','This product, its packaging and its price are illustrative. The brand will supply verified catalogue details before launch.',true)}${acc('Ingredients & directions','Final formulation, usage instructions, cautions and product claims are pending client confirmation.')}${acc('Delivery & returns','Delivery charges and returns shown in the cart are prototype examples, not confirmed policies.')}<a href="#/consult" class="link" style="margin-top:20px">Need a little guidance? ${flowArrow()}</a></div></div><div class="flow-heading" style="margin-top:65px"><h2>A little more to explore.</h2></div><div class="grid g4">${P.filter(x=>x.cat===p.cat&&x.id!==p.id).slice(0,4).map(pcard).join('')}</div></div></section>`;
};
Journal=function(){return phero('Journal','A little knowledge.<br>A little better care.','Thoughtful notes on skin, hair and the details behind everyday care.','Journal')+`<section class="flow-section"><div class="wrap"><div class="flow-tabs" aria-label="Journal categories">${['All','Skin','Hair','Ingredients','Gifting'].map((c,i)=>`<button data-flowjournal="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><div class="flow-journal-grid" id="flowJournal">${flowCards(flowArticles)}</div><p class="flow-sample">Sample editorial content. Clinical review and final authorship are pending before publication.</p></div></section>`};
Article=function(id){const a=flowArticles.find(x=>x.id===id)||flowArticles[0];return `<section class="flow-section"><div class="wrap"><article class="flow-article"><a href="#/journal" class="link">Back to the Journal ${flowArrow()}</a><h1>${a.title}</h1><p class="muted" style="font-size:14px">${a.cat} · ${a.read} min read · Sample editorial</p>${photo(a.pic,a.title)}<p>${a.intro}</p>${a.parts.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join('')}<p class="flow-sample">Prototype educational content, not individualized medical advice. Final clinical review and attribution are pending.</p><a class="btn btn-teal" href="#/consult">Explore a consultation</a></article></div></section>`};
About=function(){return phero('About','Care that<br>feels human.','Skin, hair and a little guidance. A thoughtful space for everyday care.','About')+`<section class="flow-section"><div class="wrap flow-book-grid"><div><h2>Warm. Clear.<br>Considered.</h2><p class="lead">A simpler way to explore skin and hair care, with room for questions and little moments of everyday care.</p><p style="margin-top:20px">This is the proposed KudaratCare experience. The brand's origin, team, formulations and values will be added in the client's own words before launch.</p><a href="#/shop" class="link">Explore our world ${flowArrow()}</a></div>${photo('hero','A warm, naturally lit everyday moment')}</div></section><section class="flow-section" style="padding-top:0"><div class="wrap"><div class="flow-steps">${[['leaf','Everyday care','A considered collection for your skin and hair.'],['steth','Room for guidance','A clear pathway to conversations about care.'],['gift','Thoughtfully shared','Wedding and corporate gifting with a personal touch.']].map(([i,h,p])=>`<div class="flow-step">${ic(i)}<b>${h}</b><p>${p}</p></div>`).join('')}</div></div></section>`};
Contact=function(){return phero('Contact','Let us start<br>a conversation.','Questions about a product, consultation or a thoughtful gift? Find your starting point below.','Contact')+`<section class="flow-section"><div class="wrap flow-book-grid"><div><h2>A little help,<br>right this way.</h2><div class="flow-steps" style="grid-template-columns:1fr">${[['shop','Shopping & orders'],['consult','Consultations'],['shop/corporate','Gifting & custom collections']].map(([path,h])=>`<a class="flow-step" href="#/${path}"><b>${h}</b><span class="link">Explore ${flowArrow()}</span></a>`).join('')}</div><p class="flow-sample">Contact details, hours and location are pending client confirmation.</p></div><form class="card" data-flowform="contact"><h3 style="font-size:25px;margin-bottom:20px">How can we help?</h3><div class="fgrid"><div class="field full"><label for="helpTopic">Choose a topic</label><select id="helpTopic" class="inp"><option>Shopping & orders</option><option>Consultations</option><option>Wedding gifting</option><option>Corporate gifting</option><option>Something else</option></select></div><div class="field full"><label for="sampleMessage">Sample message</label><textarea class="inp" id="sampleMessage" maxlength="500" placeholder="Try a sample message. Please do not include personal or medical information."></textarea></div><div class="full"><button class="btn btn-teal btn-block">Preview message ${flowArrow()}</button><p style="font-size:13px;margin-top:14px" class="muted">Prototype only. Nothing is sent or saved.</p></div></div></form></div></section>`};
Login=function(){return `<section class="flow-auth">${photo('hero','Illustrative warm everyday portrait')}<div class="flow-auth-copy"><span class="eyebrow">Your care, in one place</span><h1>A little space<br>for you.</h1><p class="lead">Explore the account experience, from your bag to your consultations.</p><button class="btn btn-teal" data-flowdemo>Open demo account ${flowArrow()}</button><button class="btn btn-ghost" type="button" data-flowalert="Real sign-in will be connected before launch. No Google authentication takes place in this preview.">Continue with Google (preview)</button><p class="flow-sample">No real sign-in, passwords or personal information are needed. Authentication and account creation will be connected before launch.</p><a href="#/shop" class="link">Keep exploring ${flowArrow()}</a></div></section>`};
Account=function(){const consults=store.get('kc_flow_consults',[]),orders=store.get('kc_orders',[]);return phero('Account','Your everyday<br>care space.','A preview of consultations, orders and your account, all in one place.','Account',`<button class="link" data-logout>Leave demo account ${ic('out')}</button>`)+`<section class="flow-section"><div class="wrap"><div class="flow-account-grid"><div class="card"><h3>Your consultation previews</h3>${consults.length?consults.map(c=>`<div class="flow-sample"><b>${escapeFlow(c.focus)}</b><br>${escapeFlow(c.date)} · ${escapeFlow(c.time)}<br>Preview only, not an appointment.</div>`).join(''):'<p class="muted">No consultation previews yet.</p>'}<a href="#/consult" class="link">Explore a consultation ${flowArrow()}</a></div><div class="card"><h3>Your care notes</h3><p class="muted">A space for your care plan after a real consultation. No medical regimen has been prescribed in this prototype.</p><a href="#/journal" class="link">Explore the Journal ${flowArrow()}</a></div></div><div class="card" style="margin-top:24px"><h3 style="font-size:24px;margin-bottom:22px">Demo order history</h3>${orders.length?orders.map(o=>`<div class="flow-sample"><b>${escapeFlow(o.id)}</b> · ${escapeFlow(o.date)}<br>${escapeFlow(o.items)}<br>${inr(o.total)} · Demo only, no purchase or delivery.</div>`).join(''):'<p class="muted">No demo orders yet. Explore the shop to try the bag and checkout.</p>'}</div></div></section>`};
Checkout=function(){if(!cart.length)return `<section class="flow-section"><div class="wrap"><h1>Your bag is waiting.</h1><p style="margin:20px 0">Explore the collection before trying checkout.</p><a href="#/shop" class="btn btn-teal">Explore the shop</a></div></section>`;const t=cartTotal();return phero('Checkout','Almost yours.','Explore the checkout experience. No payment or personal details are required.','Checkout')+`<section class="flow-section"><div class="wrap flow-book-grid"><form class="card" data-form="checkout"><h2 style="font-size:28px">Preview checkout</h2>${flowSample}<div class="flow-sample">Delivery details and payments will be connected in the production site. The sample shipping estimate is ${t>=999?'free':inr(79)}.</div><button class="btn btn-teal btn-block" type="submit">Create demo order ${flowArrow()}</button><a class="link" href="#/shop">Continue exploring</a></form><div class="card"><h3 style="font-size:25px;margin-bottom:24px">Your bag</h3>${cart.map(i=>`<div class="citem"><div class="th">${art(i.type)}</div><div><b>${escapeFlow(i.name)}</b><small>Quantity ${i.q}</small></div><b>${inr(i.price*i.q)}</b></div>`).join('')}<div class="sumrow" style="margin-top:22px"><b>Sample total</b><b>${inr(t+(t>=999?0:79))}</b></div></div></div></section>`};
Placed=function(id){return `<section class="flow-section"><div class="wrap" style="max-width:650px;text-align:center"><div style="display:flex;justify-content:center;margin-bottom:25px">${ic('check')}</div><h1>Preview complete.</h1><p class="lead" style="margin:22px auto">Demo order ${escapeFlow(id)} has been saved in this browser. No purchase, payment or delivery takes place.</p><a class="btn btn-teal" href="#/account">View demo account</a><a class="link" style="display:flex;justify-content:center;margin-top:15px" href="#/shop">Keep exploring ${flowArrow()}</a></div></section>`};
const oldChrome=chrome;
chrome=function(path){oldChrome(path);const base='#/'+(path.split('/')[1]||'');$('#nav').innerHTML=[['#/consult','Consult'],['#/shop','Shop'],['#/shop/wedding','Gifting'],['#/journal','Journal'],['#/about','About'],['#/contact','Contact']].map(([h,t])=>`<a href="${h}" class="${h===base?'active':''}">${t}</a>`).join('');$('#acctPill').setAttribute('aria-label',store.get('kc_user',null)?'My demo account':'Sign-in preview');$('#acctPill').innerHTML=ic('user')};
document.addEventListener('click',e=>{
 const t=e.target.closest('button,a');if(!t)return;const d=t.dataset;
 if(d.flowcat){flowCategory=d.flowcat;$('#flowCategories').innerHTML=flowCategoryCards();$('#flowCategories').setAttribute('aria-labelledby','tab-'+flowCategory);$$('[data-flowcat]').forEach(b=>b.setAttribute('aria-selected',b.dataset.flowcat===flowCategory))}
 if(d.flowjournal){$('#flowJournal').innerHTML=flowCards(flowArticles.filter(a=>d.flowjournal==='All'||a.cat===d.flowjournal));$$('[data-flowjournal]').forEach(b=>b.setAttribute('aria-pressed',b===t))}
 if(d.flowdemo!==undefined){store.set('kc_user',{name:'Demo Guest',email:''});location.hash='#/account'}
 if(d.flowalert){e.preventDefault();toast(d.flowalert)}
 if(d.toast&&/sent|emailed|WhatsApp|opens/i.test(d.toast)){e.preventDefault();e.stopImmediatePropagation();toast('Preview only. Nothing is sent, booked or connected.')}
},true);
document.addEventListener('input',e=>{if(['bNames','bNote','q'].includes(e.target.id))e.target.value=e.target.value.replace(/[<>&"']/g,'')},true);
document.addEventListener('submit',e=>{
 const k=e.target.dataset.flowform;if(!k)return;e.preventDefault();e.stopImmediatePropagation();
 if(k==='booking'){const f=new FormData(e.target),date=f.get('date');const c={focus:f.get('focus'),date,time:f.get('time')};store.set('kc_flow_consults',[c,...store.get('kc_flow_consults',[])]);e.target.innerHTML=`<h3 style="font-size:27px">Your preview is ready.</h3><p style="margin:22px 0">${escapeFlow(c.focus)} on ${escapeFlow(c.date)} at ${escapeFlow(c.time)}.</p>${flowSample}<a class="btn btn-teal" href="#/account">View demo account</a>`}
 else{e.target.reset();toast(k==='newsletter'?'Newsletter preview complete. No email is sent or saved.':'Preview complete. Nothing has been sent or saved.')}
},true);
/* Dialog focus management and keyboard tabs. */
let flowOpener;
const flowOpen=openDrawer,flowClose=closeAll;
openDrawer=function(id){flowOpener=document.activeElement;flowOpen(id);const d=$('#'+id);d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.querySelector('button,a')?.focus()};
closeAll=function(){const was=$('.drawer.open');flowClose();$$('.drawer').forEach(d=>{d.removeAttribute('aria-modal');d.removeAttribute('role')});if(was&&flowOpener?.isConnected)flowOpener.focus()};
document.addEventListener('keydown',e=>{
 const d=$('.drawer.open');if(d&&e.key==='Tab'){const nodes=$$('button,a,input,select',d).filter(x=>!x.disabled&&x.offsetParent!==null);if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
 const t=e.target;if(t.matches('[data-flowcat]')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=$$('[data-flowcat]');tabs[(tabs.indexOf(t)+(e.key==='ArrowRight'?1:2))%3].click();tabs[(tabs.indexOf(t)+(e.key==='ArrowRight'?1:2))%3].focus()}
});
/* All display content is illustrative; no fake ratings, credentials or promises. */
route();
